# Generated by Django 4.0.6 on 2022-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=45)),
                ('date', models.CharField(max_length=45)),
                ('reason', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'employee_leave',
            },
        ),
        migrations.CreateModel(
            name='EmployeesReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=45)),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=45)),
                ('empid', models.CharField(max_length=45)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'leave',
            },
        ),
    ]
